services:
    # app.admin.form:
    #     class: AdminBundle\Admin\F_FormAdmin
    #     arguments: [~, AdminBundle\Entity\F_Form, ~]
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "Site", label: "Formulaires" }
    #     public: true
    # app.admin.form_field:
    #     class: AdminBundle\Admin\F_FormFieldAdmin
    #     arguments: [~, AdminBundle\Entity\F_FormField, ~]
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "Site", label: "Form_Field" }
    #     public: true
    # app.admin.form_field_rights:
    #     class: AdminBundle\Admin\F_FormFieldRightsAdmin
    #     arguments: [~, AdminBundle\Entity\F_FormFieldRights, ~]
    #     tags:
    #         - { name: sonata.admin, manager_type: orm, group: "Site", show_in_dashboard: false}
    #     public: true
        
    app.admin.dblog:
        class: AdminBundle\Admin\DBLogAdmin
        #arguments: [~, AdminBundle\Entity\DBLog, AdminBundle\Controller\MigrationCRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Outil, label: DBLog }
        arguments:
            - null
            - AdminBundle\Entity\DBLog
            - AdminBundle:DBLogCRUD
        calls:
            - [ setTranslationDomain , [AdminStoreReceiptReceiptBundle]]
        public: true

    app.admin.dblogcorrespondence:
        class: AdminBundle\Admin\DBLogCorrespondenceAdmin
        arguments: [~, AdminBundle\Entity\DBLogCorrespondence, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Outil, label: MigrationID }
        public: true

    import.csvtoarray:
        class: AdminBundle\Services\ConvertCsvToArray