# Site services for administration:

services:
  app.admin.article:
    class: SiteBundle\Admin\ArticleAdmin
    arguments: [~, SiteBundle\Entity\Article, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Actualités" }
    public: true

  app.admin.comment:
    class: SiteBundle\Admin\CommentAdmin
    arguments: [~, SiteBundle\Entity\Comment, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Commentaires" }
    public: true

  app.admin.lien:
    class: SiteBundle\Admin\LienAdmin
    arguments: [~, SiteBundle\Entity\Lien, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Liens" }
    public: true